import { Lesson, Exam, Question, LiveSession, Complaint } from './types';

export const lessons: Lesson[] = [
  {
    id: 1,
    title: 'مقدمة في الرياضيات - الأعداد الصحيحة',
    description: 'تعلم أساسيات الأعداد الصحيحة وعملياتها الحسابية',
    duration: '45 دقيقة',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnail: '',
    isCompleted: false,
    isVideoWatched: false,
    isQuizPassed: false,
    quiz: [
      {
        id: 1,
        question: 'ما هو ناتج: 5 + (-3)؟',
        options: ['2', '8', '-2', '-8'],
        correctAnswer: 0,
      },
      {
        id: 2,
        question: 'ما هو ناتج: (-4) × (-2)؟',
        options: ['-8', '8', '-6', '6'],
        correctAnswer: 1,
      },
      {
        id: 3,
        question: 'أي من الأعداد التالية عدد سالب؟',
        options: ['0', '7', '-3', '15'],
        correctAnswer: 2,
      },
    ],
  },
  {
    id: 2,
    title: 'المعادلات الخطية',
    description: 'فهم وحل المعادلات الخطية ذات المجهول الواحد',
    duration: '50 دقيقة',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnail: '',
    isCompleted: false,
    isVideoWatched: false,
    isQuizPassed: false,
    quiz: [
      {
        id: 1,
        question: 'حل المعادلة: 2x + 4 = 10',
        options: ['x = 3', 'x = 5', 'x = 7', 'x = 2'],
        correctAnswer: 0,
      },
      {
        id: 2,
        question: 'ما هي المعادلة الخطية؟',
        options: ['x² + 2 = 0', '3x + 1 = 7', 'x³ = 8', '√x = 4'],
        correctAnswer: 1,
      },
      {
        id: 3,
        question: 'حل المعادلة: 5x - 10 = 0',
        options: ['x = 5', 'x = -2', 'x = 2', 'x = 10'],
        correctAnswer: 2,
      },
    ],
  },
  {
    id: 3,
    title: 'الهندسة - المثلثات',
    description: 'دراسة خصائص المثلثات وأنواعها',
    duration: '55 دقيقة',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail: '',
    isCompleted: false,
    isVideoWatched: false,
    isQuizPassed: false,
    quiz: [
      {
        id: 1,
        question: 'ما مجموع زوايا المثلث؟',
        options: ['90°', '180°', '270°', '360°'],
        correctAnswer: 1,
      },
      {
        id: 2,
        question: 'المثلث الذي جميع أضلاعه متساوية يسمى:',
        options: ['متساوي الساقين', 'متساوي الأضلاع', 'قائم الزاوية', 'مختلف الأضلاع'],
        correctAnswer: 1,
      },
      {
        id: 3,
        question: 'في المثلث القائم، الضلع الأطول يسمى:',
        options: ['القاعدة', 'الارتفاع', 'الوتر', 'الضلع المجاور'],
        correctAnswer: 2,
      },
    ],
  },
  {
    id: 4,
    title: 'الإحصاء والاحتمالات',
    description: 'مفاهيم أساسية في الإحصاء والاحتمالات',
    duration: '40 دقيقة',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnail: '',
    isCompleted: false,
    isVideoWatched: false,
    isQuizPassed: false,
    quiz: [
      {
        id: 1,
        question: 'ما هو المتوسط الحسابي للأعداد: 2, 4, 6, 8؟',
        options: ['4', '5', '6', '20'],
        correctAnswer: 1,
      },
      {
        id: 2,
        question: 'احتمال ظهور العدد 6 عند رمي حجر نرد:',
        options: ['1/2', '1/3', '1/6', '1/4'],
        correctAnswer: 2,
      },
      {
        id: 3,
        question: 'الوسيط لمجموعة البيانات: 3, 5, 7, 9, 11 هو:',
        options: ['5', '7', '9', '35'],
        correctAnswer: 1,
      },
    ],
  },
  {
    id: 5,
    title: 'الدوال والعلاقات',
    description: 'فهم مفهوم الدوال وتمثيلها البياني',
    duration: '60 دقيقة',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnail: '',
    isCompleted: false,
    isVideoWatched: false,
    isQuizPassed: false,
    quiz: [
      {
        id: 1,
        question: 'إذا كانت f(x) = 2x + 1، فما قيمة f(3)؟',
        options: ['5', '6', '7', '8'],
        correctAnswer: 2,
      },
      {
        id: 2,
        question: 'ما هو مجال الدالة f(x) = 1/x؟',
        options: ['جميع الأعداد', 'الأعداد الموجبة', 'جميع الأعداد ما عدا الصفر', 'الأعداد السالبة فقط'],
        correctAnswer: 2,
      },
      {
        id: 3,
        question: 'رسم الدالة الخطية يكون:',
        options: ['منحنى', 'خط مستقيم', 'دائرة', 'قطع مكافئ'],
        correctAnswer: 1,
      },
    ],
  },
];

export const exams: Exam[] = [
  {
    id: 1,
    title: 'امتحان منتصف الفصل - رياضيات',
    subject: 'رياضيات',
    duration: '60 دقيقة',
    totalQuestions: 20,
    isAvailable: true,
    questions: [
      { id: 1, question: 'ما هو ناتج: 15 × 4؟', options: ['50', '55', '60', '65'], correctAnswer: 2 },
      { id: 2, question: 'جذر المعادلة: x + 7 = 12', options: ['3', '4', '5', '6'], correctAnswer: 2 },
      { id: 3, question: 'ما هو 25% من 200؟', options: ['25', '50', '75', '100'], correctAnswer: 1 },
      { id: 4, question: 'مساحة مستطيل طوله 5 وعرضه 3:', options: ['8', '15', '16', '20'], correctAnswer: 1 },
      { id: 5, question: 'ما هو العدد الأولي؟', options: ['4', '6', '7', '9'], correctAnswer: 2 },
    ],
  },
  {
    id: 2,
    title: 'امتحان نهائي - هندسة',
    subject: 'هندسة',
    duration: '90 دقيقة',
    totalQuestions: 30,
    isAvailable: true,
    questions: [
      { id: 1, question: 'محيط دائرة نصف قطرها 7 (π=22/7):', options: ['22', '44', '88', '154'], correctAnswer: 1 },
      { id: 2, question: 'مساحة مربع طول ضلعه 6:', options: ['12', '24', '36', '48'], correctAnswer: 2 },
      { id: 3, question: 'عدد أوجه المكعب:', options: ['4', '6', '8', '12'], correctAnswer: 1 },
      { id: 4, question: 'حجم مكعب طول ضلعه 3:', options: ['9', '18', '27', '36'], correctAnswer: 2 },
      { id: 5, question: 'عدد أضلاع المسدس:', options: ['5', '6', '7', '8'], correctAnswer: 1 },
    ],
  },
  {
    id: 3,
    title: 'امتحان تجريبي - جبر',
    subject: 'جبر',
    duration: '45 دقيقة',
    totalQuestions: 15,
    isAvailable: false,
    questions: [],
  },
];

export const questions: Question[] = [
  {
    id: 1,
    studentName: 'أحمد محمد',
    subject: 'رياضيات',
    question: 'كيف أحل المعادلات التربيعية بطريقة التحليل؟',
    date: '2024-01-15',
    isAnswered: true,
    replies: [
      {
        id: 1,
        teacherName: 'د. سارة أحمد',
        reply: 'لتحليل المعادلة التربيعية ax² + bx + c = 0، ابحث عن عددين حاصل ضربهما يساوي a×c ومجموعهما يساوي b. ثم اكتب المعادلة على شكل (x + m)(x + n) = 0',
        date: '2024-01-15',
      },
    ],
  },
  {
    id: 2,
    studentName: 'فاطمة علي',
    subject: 'هندسة',
    question: 'ما الفرق بين التشابه والتطابق في المثلثات؟',
    date: '2024-01-16',
    isAnswered: true,
    replies: [
      {
        id: 1,
        teacherName: 'أ. خالد عمر',
        reply: 'التطابق يعني أن المثلثين متماثلان تماماً في الأضلاع والزوايا. أما التشابه فيعني أن الزوايا متساوية لكن الأضلاع متناسبة وليست بالضرورة متساوية.',
        date: '2024-01-16',
      },
    ],
  },
  {
    id: 3,
    studentName: 'محمد سعيد',
    subject: 'إحصاء',
    question: 'متى نستخدم الانحراف المعياري بدلاً من المدى؟',
    date: '2024-01-17',
    isAnswered: false,
    replies: [],
  },
  {
    id: 4,
    studentName: 'نورة حسن',
    subject: 'رياضيات',
    question: 'أريد شرحاً مبسطاً لمفهوم النهايات في التفاضل',
    date: '2024-01-18',
    isAnswered: false,
    replies: [],
  },
];

export const liveSessions: LiveSession[] = [
  {
    id: 1,
    title: 'حل مسائل المعادلات التفاضلية',
    teacher: 'د. سارة أحمد',
    subject: 'رياضيات',
    date: '2024-01-20',
    time: '10:00 ص',
    isLive: true,
    viewers: 45,
  },
  {
    id: 2,
    title: 'مراجعة الهندسة التحليلية',
    teacher: 'أ. خالد عمر',
    subject: 'هندسة',
    date: '2024-01-20',
    time: '2:00 م',
    isLive: true,
    viewers: 32,
  },
  {
    id: 3,
    title: 'أسئلة وإجابات - الإحصاء',
    teacher: 'د. محمد الفهد',
    subject: 'إحصاء',
    date: '2024-01-21',
    time: '11:00 ص',
    isLive: false,
    viewers: 0,
  },
  {
    id: 4,
    title: 'ورشة عمل - حل الامتحانات السابقة',
    teacher: 'أ. ليلى سالم',
    subject: 'رياضيات',
    date: '2024-01-22',
    time: '4:00 م',
    isLive: false,
    viewers: 0,
  },
];

export const complaints: Complaint[] = [
  {
    id: 1,
    studentName: 'عبدالله خالد',
    type: 'مشكلة تقنية',
    subject: 'الفيديو لا يعمل',
    message: 'عند محاولة تشغيل فيديو الحصة الثالثة، يظهر خطأ ولا يمكنني المشاهدة',
    date: '2024-01-14',
    status: 'resolved',
  },
  {
    id: 2,
    studentName: 'مريم أحمد',
    type: 'استفسار',
    subject: 'مواعيد الامتحانات',
    message: 'أريد معرفة مواعيد الامتحانات النهائية بالضبط',
    date: '2024-01-15',
    status: 'in-progress',
  },
  {
    id: 3,
    studentName: 'يوسف محمد',
    type: 'شكوى',
    subject: 'جودة البث المباشر',
    message: 'البث المباشر يتقطع كثيراً ولا يمكنني متابعة الشرح بشكل جيد',
    date: '2024-01-16',
    status: 'pending',
  },
];
